name: "Tests"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  validate-spi-manifest:
    name: Validate SPI Manifest
    runs-on: macos-13
    env:
      VALIDATE_SPI_MANIFEST: YES
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Validate SPI Manifest
      run: swift package plugin validate-spi-manifest
  test-macos:
    name: Test macOS (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        xcode: ["15.0", "14.3.1", "14.0.1", "13.4.1"]
        include:
        - xcode: "15.0"
          macos: macOS-13
        - xcode: "14.3.1"
          macos: macOS-13
        - xcode: "14.0.1"
          macos: macOS-12
        - xcode: "13.4.1"
          macos: macOS-12
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run Tests
      run: swift test
  test-linux:
    name: Test Linux (Swift ${{ matrix.swift }})
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.8", "5.7", "5.6"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run Tests
      run: swift test
